services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    # volumes: 
    #   - "./db:/data/db"

  flask:
    build: ./app/
    ports:
      - "5000:5000"
    volumes:
      - "./app/:/app/"
